### ISSUE TITLE
rails console doesn't work with pry-rails

### ISSUE THREAD

**Issue by okuramasafumi** [rails/spring#129]
In projects using pry-rails, `<spring rails console>` command doesn't work.
My env: OSX10.6.8, rails3.2.12, ruby1.9.3p392, pry-rails0.2.2, spring0.0.8

Error message says:
/Users/Masafumi/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/irb/completion.rb:11:in '<top (required)>': IRB is not a module (TypeError)
from /Users/Masafumi/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/spring-0.0.8/lib/spring/commands.rb:162:in 'setup'
(I cut most of the error messages since it is so long)

In pry-rails gem, it assigns the constant `Pry` to `Rails::Console::IRB`. This gem works fine without spring.

I found zeus has the same problem which has not been solved yet ( https://github.com/burke/zeus/issues/155 ).
How can I use spring and pry-rails at the same time?

**Comment by clarkewd** [comment]
I also removed the code in `development.rb` but had to add `pry-rails` to my `Gemfile` as I previously only had `pry`
