### ISSUE TITLE
Already initialized constant

### ISSUE THREAD

**Issue by divineforest** [rails/spring#175]
I receive

```
/Users/.../app/services/distributed_updater.rb:10: warning: already initialized constant TOTAL_TIME
```

and a lot of other warnings about already initialized constants in other files in app/services dir when run command (spring rails c, spring rails s, etc).

There is a simple class in distributed_updater.rb

``` ruby
class DistributedUpdater
  TOTAL_TIME  = 20.hours
  INTERVAL = 2.minutes
```

**Comment by brauliobo** [comment]
@divineforest can you please explain the fix?

**Comment by divineforest** [comment]
Hey @brauliobo ! It was almost 4 years ago so I will hardly remember it but it's something like double require-ing the file. Anyway, it's personal.
