### ISSUE TITLE
Failing tests when running rspec under spring

### ISSUE THREAD

**Issue by elitalon** [rails/spring#209]
Hi,

I am running the following command to execute [some tests](https://github.com/elitalon/numera/blob/5c6fa2418b9d23e6bf1fc8899519a3a53446aede/spec/models/user_spec.rb):

`spring rspec spec/models`

and three test fails:

```
1) User should have secure password
     Failure/Error: it { should have_secure_password }
     NoMethodError:
       undefined method `has_secure_password?' for #<User:0x007f807da9b5c8>
     # ./spec/models/user_spec.rb:16:in `block (2 levels) in <top (required)>'

  2) User#save when email address is already taken 
     Failure/Error: it { should validate_uniqueness_of(:email) }
     NoMethodError:
       undefined method `validate_uniqueness_of' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_4::Nested_6:0x007f807b352430>
     # ./spec/models/user_spec.rb:62:in `block (4 levels) in <top (required)>'

  3) User#save when email address is already taken with equivalent email address 
     Failure/Error: it { should validate_uniqueness_of(:email) }
     NoMethodError:
       undefined method `validate_uniqueness_of' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_4::Nested_6::Nested_1:0x007f807af7de90>
     # ./spec/models/user_spec.rb:68:in `block (5 levels) in <top (required)>'
```

However, all tests pass when running them outside spring (`rspec spec/models`, I am not using the binstub).

I honestly don't know if it's something related to `shoulda-matchers`. But it seems spring is missing to load something.

Thanks

**Comment by rodrigomageste** [comment]
Thank you @kmamykin and @jonleighton

**Comment by davidcpell** [comment]
thanks @kmamykin that worked like a charm

**Comment by AntonTrapp** [comment]
Thanks @kmamykin, as @davidcpell mentioned the order of rspec-rails has nothing to do with the failure and it does not solve the problem. The manual require does!
@jonleighton: would be great to edit your posting as everybody with the same problem tries out the not-working solution first ;)
