### ISSUE TITLE
Spring hangs when it can't connect to the server.

### ISSUE THREAD

**Issue by jcoyne** [rails/spring#265]
It should have a timeout.

```
^C/Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/client/run.rb:47:in `gets': Interrupt
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/client/run.rb:47:in `verify_server_version'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/client/run.rb:19:in `call'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/client/command.rb:7:in `call'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/client/rails.rb:23:in `call'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/client/command.rb:7:in `call'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/client.rb:26:in `run'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/bin/spring:32:in `<top (required)>'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/binstub.rb:11:in `load'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/spring-1.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/justin/.rbenv/versions/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/justin/workspace/blacklight/spec/internal/bin/spring:16:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'
```

**Comment by romul** [comment]
Looks like this issue is still active for spring 1.3.1

**Comment by TheRealGuardDogGPS** [comment]
I am having this issue with Rails 4. I run rails destroy controller some_controller, which removes the controller and the associating view files, and things seemed fine. However, next day I picked up where I left off and I try to use the generate or destroy command again and it just hangs. I press ctr + c and it gives me this:

.rvm/gems/ruby-2.1.2@core/gems/spring-1.1.3/lib/spring/client/run.rb:54:in `gets': Interrupt

Unfortunately spring stop does not work. It still hangs afterward.

**Comment by TheRealGuardDogGPS** [comment]
I had to reboot the computer!

**Comment by ryanjones** [comment]
Just ran into this w/ spring (1.3.6) & rails (4.2.3). 

@jonleighton - Here's the steps to reproduce the bug (make sure to have pry installed in your rails app):
1. Put a binding.pry in config/environments/development.rb's config block
2. Run ```bin/rails c``` (it will hang)
3. Open a new terminal and kill that rails console process
4. Remove binding.pry from config/environments/development.rb 
5. Run ```bin/rails c``` (it will hang forever) - Ctrl-C will drop the same backtrace as above

Let me know if you need any other details. I've been able to replicate it a few times now. ```spring stop``` worked for me and allowed me to to run ```bin/rails c``` successfully.

**Comment by ismailfaruqi** [comment]
I am experiencing the same thing with @ryanjones ...

**Comment by skwp** [comment]
Experiencing spring hangs consistently when using `spring rspec`, typically on classes in a sub-mounted Grape application (we have an app/api subdirectory containing the grape app). Adding this directory using `Spring.watch` does not seem to help. The tests run once and hang the second time.

**Comment by mmatusSVK** [comment]
It helps me too, but instead of $spring stop, I used $bin/spring stop :)

**Comment by kashif-umair** [comment]
@demisx, thanks. Your proposed solution worked like a charm for me :)

**Comment by alienspaces** [comment]
Happened for me today @demisx solution worked. Would like to understand what is happening though as my tests were hanging..
```
$ ./bin/spring -v
Spring version 1.7.1
$ rails -v
Rails 5.0.0.rc1
```

**Comment by babassmine** [comment]
installing `has_secure_token` caused this for me. Luckily I was able to find this thread.

**Comment by hbin** [comment]
Got hangs while creating app by my [rails-boilerplate](https://github.com/hbin/rails-boilerplate), [run 'spring stop'](https://github.com/hbin/rails-boilerplate/blob/master/template.rb#L17) before `generate` solve this.

**Comment by fabiode** [comment]
happens with me every time I exchange branches in git using a binding.pry as well =(

**Comment by michaeldever** [comment]
I have had an issue like this: if I create a project, delete it, then create a project with the same name, the likes of `rails g` hangs.

**Comment by mirzalazuardi** [comment]
When I run rails console and doesn't respond anything(just blank, without error).
 this solution also solved my problem. Thanks
