### ISSUE TITLE
App processes hanging around

### ISSUE THREAD

**Issue by jonleighton** [rails/spring#290]
I've observed situations where processes don't die properly.

In particular I've noticed app processes hanging on when the server process has died. It seems the procedure for the app process exiting is buggy. Need to consider how it may be buggy, and possibly add extra safeguards. (It probably doesn't ever make sense for the app process to outlive the server process.)

Possibly related to #278.

**Comment by rally25rs** [comment]
I just had this happen too (on OSX):

```
$ ps
  PID TTY           TIME CMD
24251 ttys000    0:00.47 spring server | management | started 19 hours ago

$ spring stop
Spring is not running
```
