### ISSUE TITLE
Client-server version mismatch when multiple versions of spring installed for the current Ruby

### ISSUE THREAD

**Issue by suan** [rails/spring#295]
I've noticed that when using multiple versions of Spring in the app's current Ruby, I get that error. This is a common occurrence because we have many apps on the same Ruby version, but possibly using dfferent versions of Spring. Even doing `bundle exec bin/rails c` or `bundle exec spring rails c` results in the same behavior.

```
$ bin/rails c
...
...
There is a version mismatch between the spring client and the server.
You should restart the server and make sure to use the same version.

CLIENT: 1.0.0, SERVER: 1.1.2
```

**Comment by morenoh149** [comment]
`spring stop` works for me.

**Comment by delef** [comment]
It's works for me too.

**Comment by Danieldizzy** [comment]
Viola it worked for me too spent the whole night on this single line...

**Comment by DemitryT** [comment]
`spring stop` :+1:

**Comment by stephenbaidu** [comment]
Thanks. Wish I had seen this earlier. ```spring stop``` worked for me as well.

**Comment by julioalucero** [comment]
It works, thanks

**Comment by baird** [comment]
spring stop *shrug*

**Comment by lancedikson** [comment]
I have the same issue:

```
Error:[rake --tasks] There is a version mismatch between the spring client and the server.
You should restart the server and make sure to use the same version.
CLIENT: 1.3.3, SERVER: 1.2.0
```

**Comment by a2k11** [comment]
spring stop works :+1:

**Comment by mhtremblay** [comment]
spring stop :+1:

**Comment by TimMoore** [comment]
`spring stop` does not work for me when going from a newer version of Spring to an older version (in my case, we updated Spring on a branch and I had to work on a fix on master).

The problem is that the Spring client is starting the wrong version of the server here:
https://github.com/rails/spring/blob/f18afb8c5ac951b7553c812482d491001b1425a8/lib/spring/client/run.rb#L68

That spawns a Ruby process that requires `spring/server`, but it doesn't do anything to lock the version of the gem that it loads, so the newest version will be required by default. Ordinarily, this job would be done by Bundler, but Spring tries to bootstrap without loading Bundler.

After the subprocess starts, Bundler is later setup, which tries to restrict the load path to the older Spring version in `Gemfile.lock`, but by this point it is too late and so it reports an error:

```
/Users/tmoore/.gem/ruby/2.1.6/gems/bundler-1.9.4/lib/bundler/runtime.rb:34:in `block in setup': You have already activated spring 1.3.4, but your Gemfile requires spring 1.3.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Users/tmoore/.gem/ruby/2.1.6/gems/bundler-1.9.4/lib/bundler/runtime.rb:19:in `setup'
	from /Users/tmoore/.gem/ruby/2.1.6/gems/bundler-1.9.4/lib/bundler.rb:122:in `setup'
	from /Users/tmoore/.gem/ruby/2.1.6/gems/bundler-1.9.4/lib/bundler/setup.rb:8:in `<top (required)>'
	from /Users/tmoore/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/tmoore/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/tmoore/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/tmoore/Projects/cultureamp/murmur/.bundle/ruby/2.1.0/gems/spring-1.3.4/lib/spring/commands.rb:33:in `<module:Spring>'
	from /Users/tmoore/Projects/cultureamp/murmur/.bundle/ruby/2.1.0/gems/spring-1.3.4/lib/spring/commands.rb:4:in `<top (required)>'
	from /Users/tmoore/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tmoore/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tmoore/Projects/cultureamp/murmur/.bundle/ruby/2.1.0/gems/spring-1.3.4/lib/spring/server.rb:9:in `<top (required)>'
	from /Users/tmoore/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/tmoore/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/tmoore/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
```

**Comment by TimMoore** [comment]
I found I could fix the problem by editing the server spawn code linked above in `client/run.rb` like this:

```ruby
        pid = Process.spawn(
          gem_env,
          "ruby",
          "-e", "gem 'spring', '#{Spring::VERSION}'; require 'spring/server'; Spring::Server.boot"
        )
```

@jonleighton do you see any problems with that approach? I'm happy to put together a pull request.

**Comment by Vipala** [comment]
spring stop works

**Comment by Vibhuti** [comment]
spring stop works for me too! :+1:

**Comment by bobzhen** [comment]
Maybe someone can try 'bundle update spring' if 'spring stop' does not work. Thanks.

**Comment by mikegazdag** [comment]
`spring stop` didn't work for me, however removing all versions of `spring` and then runing `bundle` again to install a single version worked.  Error seems to only happen when multiple versions are installed (`1.3.3` and `1.3.4` for me).

**Comment by InsomniaNoir** [comment]
I pulled up `gem list` and found `spring (1.3.5, 1.3.4)`. I ran `gem uninstall 1.3.4`, was prompted with:

` Select gem to uninstall:`
` ` ` 
1. spring-1.3.4  
2. spring-1.3.5  
3. All versions
`  ` `

I selected 1, ran bundle install, problem solved.

**Comment by knu** [comment]
It is definitely not desirable to have to manually run `gem uninstall spring` or even `spring stop` when Spring is almost always management-free.  When dealing with many projects, if one of them decided to upgrade spring the rest would need to follow or get this error.
I'd love @TimMoore's solution to be integrated. :+1:

**Comment by marten** [comment]
I agree with this. @TimMoore's solution seems a lightweight change to make, and solves the issue. Hopefully it'll get merged before it needs to rebased again.

**Comment by mediafinger** [comment]
I encountered the same issue today:

`You have already activated spring 1.3.5, but your Gemfile requires spring 1.3.4. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)`

Prepending `bundle exec` didn't help (I was doing that already).

`spring stop` & `spring restart` did not help.

So I had to run `bundle update spring` to fix my issue (which most probably originated when playing around with updated gem versions and then discarding the changes later). But as I would preferred to just tell spring to use the older version of my Gemfile, I was not happy with this fix.

So I reverted the changes in my Gemfile.lock and run `gem uninstall spring` to uninstall the newer version of spring. Running `spring stop` & `spring restart` allowed be to finally run `bundle exec rails console` without any error message.

Overall it would be great, if spring would fallback to the version set in Gemfile.lock when it is available on the system.

**Comment by jonleighton** [comment]
@mediafinger Are you using binstubs?

**Comment by mediafinger** [comment]
@jonleighton yes, in this project I do.

**Comment by s12chung** [comment]
having the same problem... http://stackoverflow.com/questions/30199075/rbenv-bundle-exec-spring-not-working

**Comment by klaussteininger** [comment]
spring stop worked for me too

**Comment by gjrevans** [comment]
@mediafinger THANK YOU! This indirectly solved my issue. When I ran 'gem uninstall spring', it asked which version I wanted to remove. Turns out I had 1.3.3 and 1.3.6 installed. Removing 1.3.6 got rid of my dependancy error.

**Comment by zxr90** [comment]
`bundle update spring ` works for me. thanks @mediafinger

**Comment by elepht** [comment]
bundle update spring works for me. thanks @mediafinger

**Comment by SafwanMarwan** [comment]
@bobzhen , @mediafinger Thank you so much

**Comment by cawel** [comment]
`spring stop` did not work for me. But @TimMoore's diagnostic seems to be spot on. For now, I have updated the `spring` gem to the latest version using `bundle update spring` and it solved my issues.

**Comment by kemingcao** [comment]
`spring stop` does not work for me, but reinstall works for me : )

**Comment by rosnk** [comment]
bundle update spring worked for me, thanks

**Comment by RanSolo** [comment]
bundle update spring :+1:

**Comment by fredmcgroarty** [comment]
bundle update spring :+1:

**Comment by hoanewton** [comment]
woohoo!! srping stop works

**Comment by RanSolo** [comment]
bundle update spring :+1:

**Comment by StevenXL** [comment]
`sprint stop` :+1:

**Comment by DavidVII** [comment]
`bundle update spring` is the only thing that worked for me :+1:

**Comment by dantesolis** [comment]
```spring stop -> bundle update spring  -> spring restart``` worked for me :+1:

**Comment by darkodosenovic** [comment]
spring stop :+1:

**Comment by jpcpamies** [comment]
I did change the version of the spring client: 1.4.4 in order to match the version of the spring server: 1.4.0 
Change this on the Gemfile
gem 'spring', '1.4.0'
And then I did bundle update on the command line.
It seems to work.

**Comment by chandracarney** [comment]
```bundle update spring``` :+1:

**Comment by igorbarbashin** [comment]
If `spring stop` doesn't work then try `bundle exec spring stop`
