### ISSUE TITLE
Both spring and rbenv use binstubs

### ISSUE THREAD

**Issue by pitosalas** [rails/spring#300]
Do they conflict? Does one defeat the other? I found that if I did `rake test` by itself I would end up running "/Users/pitosalas/.rbenv/shims/rails" and if i do `bin/rake test` it seems to use spring (goes much faster.) How do I combine them so I don't have to include 'bin' but still get the advantage of the rbenv context?

**Comment by hayesgm** [comment]
@jonleighton Do you have a location in the docs to answer the original inquiry? I believe how to use a gem meant for development environments is a valid question on how to use the gem in development environments.
