### ISSUE TITLE
rails console or runner run in production mode by '-e production' may have bug

### ISSUE THREAD

**Issue by gazeldx** [rails/spring#348]
`$ rails console -e production`
Then I got: 
Loading production environment (Rails 4.1.4)
Then I query something, 
`2.1.2 :001 > SomeModel.all.count`
I found that I got result which is queried from database  'my_project_development'
I expect the return result from  'my_project_production'

`$ rails runner -e production ...`
has the same problem.

**Comment by sonalkr132** [comment]
@gazeldx Can you please check if you can still reproduce this issue? I couldn't. I used rails 4.1.4 and spring 1.5.0

```
$ spring rails console -e production
Loading production environment (Rails 4.1.4)
2.2.1 :001 > Project.all
 => #<ActiveRecord::Relation []> 

$ spring rails console
Loading development environment (Rails 4.1.4)
2.2.1 :001 > Project.all
  Project Load (0.9ms)  SELECT "projects".* FROM "projects"  WHERE "projects"."deleted_at" IS NULL
 => #<ActiveRecord::Relation [ #<Project id: 1...>]>
```

**Comment by gazeldx** [comment]
Now I am using spring (1.2.0) and Rails4.1.7 .
Everything works fine.
@sonalkr132
