### ISSUE TITLE
Spring.watch: undefined method watch

### ISSUE THREAD

**Issue by ramontayag** [rails/spring#349]
You have to `require "spring/watcher"` for it to work

**Comment by sonalkr132** [comment]
@ramontayag I could not duplicate your issue (using spring 1.5).
I did following:

1. Add `gem "spring", group: :development` to gem file and `bundle install`.
2.  'springify' the executables  `bundle exec spring binstub --all`
3. Launch rails console with `spring rails c`
4. Try given method `Spring.watch`
```
2.2.1 :001 > Spring.watch
 => 1449733497.4481788 
```

**Comment by ramontayag** [comment]
Thanks for checking this @sonalkr132. Since this issue is very old, I'll just close it. If it's still an issue I'll open it again.
