### ISSUE TITLE
bundler options github and git causes warning

### ISSUE THREAD

**Issue by grrrisu** [rails/spring#352]
In one of my projects I got this warning from bundler every time I run the application:
```
git://github.com/grrrisu/Simulator.git (at master) is not yet checked out. Run `bundle install` first.
```
But the gem is installed correctly under $GEM_HOME/bundler/gems. Also **bundle list** shows the gem with the correct ref.

Every gem, that I require with with the **github** or **git** option in my Gemfile causes this warning. Digging down the problem, I discovered that unsetting the **ENV["GEM_HOME"]** in [bin/spring](https://github.com/rails/spring/blob/master/lib/spring/client/binstub.rb#L41) caused it. Now that no GEM_HOME is set, bundler tries to look up the gem in my_application/bundler/gems directory, which in my case does not exist and causes the warning. As soon as I remove the line from bin/spring, bundler works again as expected.

**Comment by monfresh** [comment]
I have the exact same problem in one of my projects, and I can't figure out what's causing it. All I know is that adding spring caused the issue. Removing the `ENV["GEM_HOME"] = ""` line from `bin/spring` fixed the issue. I tried to reproduce this issue with another project that uses spring by adding a git-sourced gem, but could not (on the same machine with RVM and rubygems-bundler).

**Comment by monfresh** [comment]
So, I narrowed it down to these two gems, but I don't know why they are causing this issue. Note that setting `ENV["GEM_HOME"] = nil` does not work in this case. The only solution while the 2 gems below are present in the Gemfile (pointing to the GitHub repo) is to completely remove the `ENV["GEM_HOME"] = ""` line.

https://github.com/omb-awong/ruby-saml/tree/encrypted-saml-support
https://github.com/omb-awong/saml_idp

**Comment by monfresh** [comment]
Going further, I narrowed it down to the `uuid` gem, which depends on `macaddr`, which in turn depends on `systemu`. So, it's down to one of those three. In my project that doesn't have any issues with github-based gems, simply adding `gem 'uuid'` to the Gemfile and running `bundle install` caused the issue when running `rails s`.

**Comment by monfresh** [comment]
I believe this is the offending line in `systemu`: https://github.com/ahoward/systemu/blob/master/lib/systemu.rb#L37
because when the error occurs, I see `no ruby in PATH/CONFIG` in the output after running `rails s`.

**Comment by monfresh** [comment]
To summarize, to reproduce this you need all of the following ingredients:

- RVM with rubygems-bundler
- any github-based gem in the Gemfile
- Spring
- a gem, such as `systemu`, that doesn't play well with the first three ingredients

Note that this is only reproducible if you run `rails s` (with rubygems-bundler installed) or `bundle exec rails s`. If you run `bin/rails s`, this issue does not happen.

**Comment by grrrisu** [comment]
@monfresh : wow, thanks for investigating the issue
To confirm your theory, I also so ```systemu``` through ```uuid``` in my Gemfile

**Comment by alecslupu** [comment]
Hello!

i am not using neither `systemu` nor `uuid`, and i get the same issue with v 1.3.0. 
I do not have any issues in v 1.2.0

**Comment by phyllisstein** [comment]
To echo @alecslupu, I've been having this very problem with v1.3.0, and none of the gems in my Gemfile depend on `systemu` or `uuid`. I am using RVM with Bundler; trying different combinations of their versions didn't help, though, till I removed the line `ENV["GEM_HOME"] = nil`, as recommended.

**Comment by t-anjan** [comment]
I have the exact same problem with the `activeadmin` gem sourced from Github.

Removing the line `ENV["GEM_HOME"] = nil` fixes the problem.

**Comment by mrfoto** [comment]
We have this problem now too. It worked with 1.2, and 1.3 breaks it. We have one gem that's relying on a git fork. If I remove that it starts working with 1.3. But we can't remove that so please investigate what's causing spring to do this.

Thanks!

**Comment by naag** [comment]
+1 on @alecslupu. We're running RVM, Ruby 2.1.5, Rails 4.2.0 and experience these problems when using guard to execute RSpec tests. As described by @grrrisu, bundler searches for the gems from Github inside application_dir/bundler/gems instead of /usr/local/rvm/... This was still fine with Spring 1.2.0. Solutions are to restrict Spring to 1.2.0 or to remove `ENV["GEM_HOME"] = nil` from bin/spring.

**Comment by jonleighton** [comment]
@alecslupu @phyllisstein @t-anjan @mrfoto Did you guys update your `bin/spring` when you upgraded?

I just upgraded an app from 1.1.3 to 1.3.0. For me, I actually had the error message initially, but when I updated my `bin/spring` (by running `spring binstub`) to replace `ENV["GEM_HOME"] = ""` with `ENV["GEM_HOME"] = nil` it started to work.

**Comment by jonleighton** [comment]
I've [fixed](https://github.com/rails/spring/commit/11b8527fee5a1de1072b9d529851bb9d85ae87b3) the issue I described and release 1.3.1. I'm unclear how that affects the people who are reporting a problem here, though. So please let me know.

**Comment by t-anjan** [comment]
@jonleighton - Yes, my `bin/spring` file already has `ENV["GEM_HOME"] = nil`. Whether it is `nil` or `""` does not matter. Just having that line causes the problem. Only commenting or removing that line fixes it.

**Comment by mrfoto** [comment]
Same as @t-anjan. Doesn't work no matter what I set `ENV["GEM_HOME"]` to. Once I remove that line, all starts to work again.

**Comment by monfresh** [comment]
Hi @jonleighton. As I [mentioned 15 days ago](https://github.com/rails/spring/issues/352#issuecomment-71576181) while investigating this issue, setting `ENV['GEM_HOME']` to `nil` is not the solution. I narrowed down the issue to the `systemu` gem, and I even provided the line number that is causing the issue. I believe the next step for you (or anyone else with the skills) is to figure out what the systemu gem is doing to cause this, and to submit a pull request so they can fix it on their end if it is a systemu bug, or come up with another fix in Spring if it is a Spring issue, such as **completely removing the `ENV['GEM_HOME']` line**.

**Comment by jonleighton** [comment]
@monfresh seems like there are two issues: the one you identified, and a regression in 1.3.0 that others have reported. They may or may not be related. My priority is to fix the regression.

Can you guys tell me what GEM_HOME and GEM_PATH contain before they are reset in bin/spring?

**Comment by eljojo** [comment]
This are my GEM_HOME and GEM_PATH:
```
$ echo $GEM_HOME
/Users/jojo/.gem/ruby/2.1.3

$ echo $GEM_PATH
/Users/jojo/.gem/ruby/2.1.3:/Users/jojo/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0
```

I'm using chruby

**Comment by phyllisstein** [comment]
Hey Jon! I'm using RVM myself, and once I've invoked my gemset `GEM_HOME` is `/usr/local/rvm/gems/ruby-head@clmp` and `GEM_PATH` is `/usr/local/rvm/gems/ruby-head@clmp:/usr/local/rvm/gems/ruby-head@global`. Hope that helps!

**Comment by mrfoto** [comment]
`ENV['GEM_HOME']` is `"/Users/mrfoto/.gem/ruby/2.2.0"`
`ENV['GEM_PATH']` is `/Users/mrfoto/.gem/ruby/2.2.0:/Users/mrfoto/.rubies/ruby-2.2.0/lib/ruby/gems/2.2.0`

I'm also using chruby, but my coworkers are on RVM and they had the same issue.

**Comment by jonleighton** [comment]
Thanks guys. Let's move to #383 to discuss this regression to keep the discussion in one place. Once it's fixed, it might be that this issue is also fixed but we'll have to wait and see.

**Comment by jonleighton** [comment]
I've fixed the regression in 1.3.2. I think this original issue (with the `systemu` gem) should also be fixed, could somebody please confirm?

**Comment by phyllisstein** [comment]
@jonleighton I was one of those seeing the issue without `systemu`, but 1.3.2 is working a treat for me. Thanks so much!

**Comment by grrrisu** [comment]
@jonleighton updated today to 1.3.2 and everything works fine again. So also the issue with ```systemu``` seems to be fixed now. Thank you!
