### ISSUE TITLE
rspec with --tag option runs different test than spring rspec with same --tag option

### ISSUE THREAD

**Issue by mskraddoc** [rails/spring#359]
Stackoverflow question here: http://stackoverflow.com/questions/26457630/rspec-with-tag-option-runs-different-test-than-spring-rspec-with-same-tag-op

Summary: Seems I have to pick between saving time using Spring or saving time skipping slow rspec tests. Can't get both.

**Comment by bogdan-dumitru** [comment]
@jonleighton I'm still getting the exact behaviour described in the issue when running:
```
spring rspec --tag ~elasticsearch
```
It fails with no results on current ``master`` and 1.2.0.

Are we sure this is fixed, or am I missing something. @mskraddoc is this working for you?
