### ISSUE TITLE
rails console will not suspend

### ISSUE THREAD

**Issue by etcetc** [rails/spring#361]
When using spring, I am unable to ctl-Z out of the rails console.  While it looks like it's in the shell, if I just hit return it goes back into the rails console.  After that, nothing makes sense as it seems to drop letters.  

```
thumbz> rails c
Loading development environment (Rails 4.1.7)
2.1.3 :001 > User
 => User (call 'User.connection' to establish a connection) 
2.1.3 :002 > 
[1]+  Stopped                 rails c
thumbz> 
2.1.3 :003 >   User
-bash: Ue: command not found
thumbz> User
NameError: undefined local variable or method `srUe' for main:Object
from (irb):3
from /Users/ff/.rvm/gems/ruby-2.1.3@rails41/gems/railties-4.1.7/lib/rails/commands/console.rb:90:in `start'
from /Users/ff/.rvm/gems/ruby-2.1.3@rails41/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
from /Users/ff/.rvm/gems/ruby-2.1.3@rails41/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in `console'
```

At this point, my only recourse is to kill the terminal shell.

This is running on Yosemite on Mac.  I have tried w/ ruby 1.9.3 and 2.1, and with rails 4.0 and 4.1.

**Comment by casper** [comment]
I have exactly the same problem. It seems the spring server is somehow attached to the PTY of the shell. So even if you suspended the spring console command, the server is still reading and writing to the PTY. 

Killing the server with `kill -HUP` frees the shell to start working again. So it's definitely the server that is causing the problem. The client should probably trap SIGTSTP and tell the server to disengage from the PTY before the client process is suspended.

**Comment by casper** [comment]
This almost fixes the problem:

```
--- lib/spring/client/run.rb      2015-01-02 11:11:40.737995931 +0200
***************
*** 95,100 ****
--- 95,112 ----
            log "got pid: #{pid}"

            forward_signals(pid.to_i)
+
+           Kernel.trap("TSTP") {
+             log "suspended"
+             Process.kill("STOP", pid.to_i)
+             Process.kill("STOP", Process.pid)
+           }
+
+           Kernel.trap("CONT") {
+             log "continued"
+             Process.kill("CONT", pid.to_i)
+           }
+
```

Only problem is you have to hit ctrl-C once after you resume. I think the suspend character (^Z) gets sent to the server and irb doesn't like that. But at least the shell doesn't go bonkers if you suspend the spring console.

**Comment by pavelz** [comment]
will this be merged soon? spring is useful except when it doesn't suspend.

**Comment by pavelz** [comment]
Still does not work, but commenting out "guard-rails" gem did help.

**Comment by casper** [comment]
> Still does not work, but commenting out "guard-rails" gem did help.

Are you sure you killed all background processes before you tested the patch? You have to manually check everything with `ps` to make sure. It's easy to leave the Spring server running accidentally, and the client will then reuse it when you think you are restarting everything.

The other options something has changed since 2015 when I tested it last time, or maybe there is some interaction with guard-rails I'm not aware of.
