### ISSUE TITLE
Support for multiuser enviroment

### ISSUE THREAD

**Issue by boblin** [rails/spring#376]
Hi,

we are couple of developers working on the same project on one server. 

    /home/user1/projectA
    /home/user2/projectA

For user1 everything works fine. But when second developer try to run spring he gets an error:

    $ spring start
    ... /gems/spring-1.1.3/lib/spring/server.rb:22:in `initialize':  Permission denied @ rb_sysopen - /tmp/spring/fe2f27a5ddf5681bb3a92fa687d7ff7f.pid (Errno::EACCES)

I found that spring uses */tmp/spring/[md5(APP_ROOT)]* for the socket and /tmp/spring/[md5(APP_ROOT)].pid for the pid file. We can't use SPRING_TMP_PATH anymore, it is not working anymore.

I suggest spring to use */tmp/spring/[md5(username + APP_ROOT)]* for the socket.

**Comment by BrackXs** [comment]
The problem is that the /tmp/spring directory is not writable for all users.
Easiest fix would be making /tmp/spring world writable.
Reintroducing SPRING_TMP_PATH should work too.

**Comment by boblin** [comment]
Thanks for workaround. It works :+1:

**Comment by BrackXs** [comment]
But this still does not solve the problem.
Whenever /tmp/spring is being deleted, the problem pops up again.
I am strongly in favour of a permanent solution.

**Comment by jonleighton** [comment]
>  Easiest fix would be making /tmp/spring world writable.

I agree with this suggestion. Patches welcome.

**Comment by kwerle** [comment]
Aren't there 2 better options?
Rails has a tmp directory - why not use that instead of the system tmp?
Why create a spring directory at all?  /tmp and Tempfile seem ideal.

**Comment by boblin** [comment]
Good point. Maybe Rails directory tmp/pids/ fits better for this. But, global /tmp/ has advantage self purging after system restart.

**Comment by jonleighton** [comment]
System `/tmp` is used because the rails `tmp` may be on a filesystem which cannot support UNIX socket files. (Spring previously used rails' `tmp` and people running under Vagrant had trouble.)

**Comment by kwerle** [comment]
That's interesting and weird.
In any case, I should think that Tempfile.new('spring') -> /tmp/spring.random would work fine - instead of /tmp/spring/random.

**Comment by jaroslawr** [comment]
Just ran into this too, +1 for using rails tmp/ folder, tmp/pids is the standard location used for this by other gems.
