### ISSUE TITLE
Run `bundle install` first

### ISSUE THREAD

**Issue by Fudoshiki** [rails/spring#380]
rails 4.2

$ rails new .
$ bundle
$ bundle exec spring binstub --all
$ rails s - ok
$ rails c
git://github.com/mongoid/mongoid (mongo-ruby-driver-2) is not yet checked out. Run `bundle install` first. - error

commented mongoid in Gemfile gives me next gem exception

**Comment by Fudoshiki** [comment]
https://github.com/rails/spring/issues/352

**Comment by jonleighton** [comment]
Please follow #352 regarding this
