### ISSUE TITLE
Possible Spring issue asking to run `bundle install` first

### ISSUE THREAD

**Issue by DaniG2k** [rails/spring#383]
I've posted this as an [issue in Bundler](https://github.com/bundler/bundler/issues/3384) as I thought it was an error with Bundler, but apparently it's not.

When I run `rails c` in development I am getting the message:

    git://github.com/radar/by_star (at master) is not yet checked out. Run `bundle install` first.

No matter how many times I run `bundle install`, I keep getting the same error message.
I've asked for some help on IRC and someone suggested I remove the following lines from **/myapp/bin/rails** (marked with "-"):

    #!/usr/bin/env ruby
    -begin
    -  load File.expand_path("../spring", __FILE__)
    -rescue LoadError
    -end
    APP_PATH = File.expand_path('../../config/application',  __FILE__)
    require_relative '../config/boot'
    require 'rails/commands'

Commenting those lines out enables me to once again use `rails c` as expected.
This leads me to think that this is a Spring issue.

Some more useful info:

    $ rails -v
    Rails 4.2.0
    $ bundle exec rails c
    git://github.com/radar/by_star (at master) is not yet checked out. Run `bundle install` first.
    $ rvm info
    Warning! PATH is not properly set up, '/Users/dani/.rvm/gems/ruby-2.2.0/bin' is not at first place,
             usually this is caused by shell initialization files - check them for 'PATH=...' entries,
             it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
             to fix temporarily in this shell session run: 'rvm use ruby-2.2.0'.

    ruby-2.2.0:

      system:
        uname:       "Darwin Danieles-MacBook-Pro-2.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64"
        system:      "osx/10.10/x86_64"
        bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)"
        zsh:         "/bin/zsh => zsh 5.0.5 (x86_64-apple-darwin14.0)"

      rvm:
        version:      "rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
        updated:      "1 hour 43 minutes 6 seconds ago"
        path:         "/Users/dani/.rvm"

      ruby:
        interpreter:  "ruby"
        version:      "2.2.0p0"
        date:         "2014-12-25"
        platform:     "x86_64-darwin14"
        patchlevel:   "2014-12-25 revision 49005"
        full_version: "ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]"

      homes:
        gem:          "/Users/dani/.rvm/gems/ruby-2.2.0"
        ruby:         "/Users/dani/.rvm/rubies/ruby-2.2.0"

      binaries:
        ruby:         "/Users/dani/.rvm/rubies/ruby-2.2.0/bin/ruby"
        irb:          "/Users/dani/.rvm/rubies/ruby-2.2.0/bin/irb"
        gem:          "/Users/dani/.rvm/rubies/ruby-2.2.0/bin/gem"
        rake:         "/Users/dani/.rvm/rubies/ruby-2.2.0/bin/rake"

      environment:
        PATH:         "/usr/local/bin:/Users/dani/.rvm/gems/ruby-2.2.0/bin:/Users/dani/.rvm/gems/ruby-2.2.0@global/bin:/Users/dani/.rvm/rubies/ruby-2.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dani/.rvm/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin"
        GEM_HOME:     "/Users/dani/.rvm/gems/ruby-2.2.0"
        GEM_PATH:     "/Users/dani/.rvm/gems/ruby-2.2.0:/Users/dani/.rvm/gems/ruby-2.2.0@global"
        MY_RUBY_HOME: "/Users/dani/.rvm/rubies/ruby-2.2.0"
        IRBRC:        "/Users/dani/.rvm/rubies/ruby-2.2.0/.irbrc"
        RUBYOPT:      ""
        gemset:       ""

Any help is much appreciated!

**Comment by miks** [comment]
same here with Spring 1.3.1

**Comment by eljojo** [comment]
Hi, I spent all my morning debugging and I can confirm that this happens too!
1.3.1 fails, 1.2.0 works normally

**Comment by DaniG2k** [comment]
I've tried to reinstall rvm, reinstall ruby, reinstall rails, reinstall all gems, still same error message :disappointed:

**Comment by jonleighton** [comment]
Hi guys, there's some discussion about this on #352. It's definitely a regression in 1.3.X.

Can somebody confirm what GEM_HOME and GEM_PATH are set to before they get changed in `bin/spring` please?

**Comment by denys281** [comment]
Have same issue.  Before `spring` installing all was fine, but just after, for `rails_admin`:
`git://github.com/sferik/rails_admin.git (at master) is not yet checked out. Run bundle install first.`

@jonleighton  I am not sure but before and after they are same

$GEM_HOME
`/home/vagrant/.rvm/gems/ruby-2.2.0`

$GEM_PATH
`/home/vagrant/.rvm/gems/ruby-2.2.0:/home/vagrant/.rvm/gems/ruby-2.2.0@global : No such file or directory`

**Comment by jonleighton** [comment]
Thanks. A bunch of people have commented on #352 as well. Seems like this issue affect RVM and chruby. I currently use rbenv hence haven't seen it myself. When I have a chance I'll try to install RVM/chruby and see if I can repro.

**Comment by jonleighton** [comment]
In #352 @mrfoto reported:

> ENV['GEM_HOME'] is /Users/mrfoto/.gem/ruby/2.2.0
> ENV['GEM_PATH'] is /Users/mrfoto/.gem/ruby/2.2.0:/Users/mrfoto/.rubies/ruby-2.2.0/lib/ruby/gems/2.2.0

Can you check what value is in `ENV['GEM_PATH']` *after* it gets set in `bin/spring`?

**Comment by mrfoto** [comment]
`/Users/mrfoto/.gem/ruby/2.2.0:/Users/mrfoto/.gem/ruby/2.2.0:/Users/mrfoto/.rubies/ruby-2.2.0/lib/ruby/gems/2.2.0`

**Comment by dmke** [comment]
@jonleighton I'm using rbenv (with rbenv-gemsets) and am affected by this issue, too...

**Comment by universal** [comment]
i yesterday tried to reproduce it on a pristine rbenv with ruby-install and ruby 2.1.5, and that combination didn't exhibit the problem. Rvm with ruby 2.1.5 and 2.1.2 did though.

**Comment by dredozubov** [comment]
I'm experience this with chruby.

**Comment by jonleighton** [comment]
1.3.2 is out which should solve this issue

**Comment by mrfoto** [comment]
@jonleighton it does. Thanks! :+1: :beers:

**Comment by glaszig** [comment]
i just jumped from 1.2.0 to 1.3.6 and had this problem (rbenv, ruby 2.2.2).
@dredozubov's suggestion fixed the issue for me:
> Regenerating binstubs with spring seems to help.

**Comment by tonyta** [comment]
@glaszig thanks for coming back here mentioning this! :+1:

**Comment by diegodesouza** [comment]
I'm having the same issue, but unsure how to go about fixing it. I'm also using rbenv.
