### ISSUE TITLE
Why is Spring for development booting up in production and consuming over half my memory?

### ISSUE THREAD

**Issue by dt1973** [rails/spring#391]
On Ruby 2.2.0p0 and Rails 4.2 -- why is Spring 1.2.0 booting up in production with two processes consuming over half my memory?

I specifically set it to development only with `gem "spring", group: :development` in my Gemfile -- but here in production I see one `ruby: spring app | production mode` and one `ruby: spring app | development mode` and I have no idea how they got there.

**Comment by onebree** [comment]
Check out this section of the app's README. It explains how to ensure spring does not run on a production server.

https://github.com/rails/spring#deployment

**Comment by dt1973** [comment]
Thank you!

In the future though, it would be nice if Spring could take care of this by itself.

**Comment by onebree** [comment]
I definitely agree -- I did the same as you, installing it under my Gemfile test group. Thankfully, my machine does not interact with deploying the production server, though.

**Comment by dt1973** [comment]
Glad I'm not the only one. Have a great weekend!

**Comment by dt1973** [comment]
It seems Spring is still being booted despite being removed from the Gemfile (together with `gem uninstall spring`) ages ago. How do I get rid of this thing?

**Comment by rafaelfranca** [comment]
If it is not installed on the server how does it start? Are you sure the
gem is not in the server?

**Comment by dt1973** [comment]
Sorry, my bundle wasn't properly updated!
