### ISSUE TITLE
Release new version to cure rails/master regression on per-test case spring usage

### ISSUE THREAD

**Issue by dhh** [rails/spring#401]
Since we can't use Spring via github bundler references, we need a release that includes the new test command, such that working with rails/master and running individual test cases can run through Spring like before.

/cc @arthurnn @rafaelfranca

**Comment by rafaelfranca** [comment]
:+1:, but I'm wondering, do we need to rush a release?

I know that it is not the case here but if every time we add a new command to Rails ([and for the next Rails 5 release it will be a lot](https://github.com/rails/rails/issues/18878)) we need to release Spring, we will have a lot of extra work.

Anyway, tests not using Spring like before is a huge problem to those who are testing master, but I'd consider it as an exception and not rush a release every new rails command we add.

**Comment by dhh** [comment]
I think we want to have as many people as possible using rails/master for
as much as possible. That's the only way we get this stuff tested. I'm
using rails/master for a new project, and I've been tripping over tons of
stuff. Let's fix it, and keep it fixed, such that running rails/master is a
reasonable proposition for the people who do want to help develop the
latest through real app usage.

If releasing Spring is a big hassle, maybe we can fix that instead? Just
make it trivial to release Spring, so there's no cost to doing so whenever
we add a new command.

**Comment by rafaelfranca** [comment]
Agree about keeping spring running against master.

Releasing spring is trivial. The extra work is remembering that every time a new command is added to rails master we need to release a new version of Spring. I already added every member of the Rails Core with release access, and I'll send an email to all the committers to tell about the need to release spring after a new command is added.

**Comment by dhh** [comment]
Sweet. Do you want to push out a new Spring as it stands now?

**Comment by rafaelfranca** [comment]
I'm doing it already. Just waiting the build to pass.

**Comment by rafaelfranca** [comment]
Released 1.3.4

**Comment by dhh** [comment]
❤️

**Comment by arthurnn** [comment]
thanks both :heart:
