### ISSUE TITLE
Print notice when client process uses Spring

### ISSUE THREAD

**Issue by mperham** [rails/spring#407]
I just burned an afternoon because something started Spring and I had no idea it was running.  It would have saved me hours if `bundle exec rails c` had printed "Using spring process 12345" when it started up so I'd known it was active.

I hear people complain about debugging mysterious problems due to out-of-date code preloaders all the time so it would seem this is a pretty common issue.  Would it be possible to add a notice?

**Comment by knu** [comment]
I agree!  It could also print when it started and when it reloaded the app, in either absolute or human readable elapsed times.

**Comment by eoinkelly** [comment]
+1 Some sort of `verbose_output = true` flag in `~/.spring.rb` would be awesome.

**Comment by jonleighton** [comment]
Yeah, I think this is probably a good idea in hindsight. My initial goal with Spring was to make it work well enough that it could be completely automatic. But it's clear that there are so many edge cases and nuances that it will never "just work" in all cases. So better to provide useful feedback.

Does somebody want to work on a PR?

**Comment by grosser** [comment]
fixed in 1.6.0
