### ISSUE TITLE
Spring constantly recreates Gemfile.lock with new versions of Bundler

### ISSUE THREAD

**Issue by chemica** [rails/spring#409]
Recent versions of Bundler (>= 1.10.0  I believe) add a bundler version number to the Gemfile.lock. You can read about some of the issues relating to this new feature here:

https://github.com/bundler/bundler/issues/3697

This can cause problems with certain Git workflows when combined with Spring. The situation appears to be this:

 - User runs a routine 'bundle install' on a project after pulling.
 - Bundler adds a new version number to the tail of the Gemfile.lock.
 - User attempts to revert this file (which is otherwise identical) in order to avoid a mess in Git or problems with stashing or rebasing.
 - Spring detects a change to Gemfile.lock and apparently re-bundles.
 - The version number is almost immediately added to the tail of the Gemfile.lock.
 - Repeat 3 times.
 - User flips table.

As can be seen from the thread above, the Bundler team don't seem to be motivated to help alleviate this issue. I'm wondering if Spring can be adapted to ignore the version number changes in the Gemfile.lock and thus make using Git a lot more sane.

**Comment by hartator** [comment]
Same issue here. I've reverted 100+ time until narrowed down to interactions between Spring and the last version of Bundler.

**Comment by rafaelfranca** [comment]
Thank you for the report but this is not a bug. You should commit your Gemfile.lock change instead of reverting like @indirect explained here https://github.com/bundler/bundler/issues/3697#issuecomment-107226816

**Comment by jhass** [comment]
So you don't accept contributor workflows as valid either. Thanks for the information.

**Comment by jhass** [comment]
Fyi, bundler did reduce the pain of this issue after all https://github.com/bundler/bundler/commit/1c3b5c6f144a1b96a205e326087212630007d773

**Comment by hartator** [comment]
The proposed workflow is something I can accept. What I don't get is why the `Gemfile.lock` get rewritten at all without explicitly call a `bundle install` or `bundle update`. If feels Bundle should respect the state of the `Gemfile.lock` or Spring shouldn't silently update the `Gemfile.lock` in the background.

**Comment by hartator** [comment]
Ha, nice that's perfect! I was actually working on do a pull request that does pretty much the same thing! :+1:
