### ISSUE TITLE
Disabling ActiveRecord throws an error

### ISSUE THREAD

**Issue by chadwtaylor** [rails/spring#421]
When running `rails console` with ActiveRecord disabled throws an error saying the development database is missing / not configured.

Had to comment out spring from Gemfile and everything is fine. Would be nice to be able to run spring when activerecord is disabled.

**Comment by grosser** [comment]
sounds like a feature that should be supported ...
can you attach a backtrace ?
can you `bundle open spring` and try out what change would be required ? <-> PR ?

**Comment by sonalkr132** [comment]
@chadwtaylor Can you please provide steps to reproduce it?

I tried
```
bundle exec railties/exe/rails new edge_app --edge -O
```
and then `rails c`. It didn't give me any error.

**Comment by chadwtaylor** [comment]
I upgraded to Rails 4.2, with ActiveRecord disabled, and the issue went away. My previous setup was Rails 3.2.

Thanks for inquiring and reminding me that this issue was still open. I think it's safe to consider this issue resolved and closed.
