### ISSUE TITLE
stdout won't be closed when error occured in preload

### ISSUE THREAD

**Issue by ypresto** [rails/spring#422]
## Summary

When error is occurred while preloading rails app, with stdout piped to another command:

- Expected: exit and return to console
- Actual: piped command does not exit until `spring stop` is run

I found this issue while developing [auto completion plugin for text editor](https://github.com/ypresto/robe-atom).

## Gem versions

rails 4.2.3
spring 1.3.6

## Steps to reproduce

1. rails new test-rails-app
1. Insert syntax error in config/application.rb (e.g. remove `end` of last line)
1. bin/rails runner 'some script' | tail
1. SyntaxError stack trace is printed out, but tail does not exit.
1. bin/spring stop will exit tail command and return to console.

This issue does not happen when syntax error is placed in 'some script', not application.rb.

**Comment by grosser** [comment]
thx for the detailed issue! 
Do you know how to fix it ?

**Comment by ypresto** [comment]
I have no idea.

I tried closing STDOUT, STDERR and STDIN at some of place (run.rb, application.rb, server.rb) but it doesn't work.
lsof says spring server process holds pipe connected to shell process even after exception occurred.

```
zsh        7405 yuya   14     PIPE 0xc2953d60d4d8f97b      16384          ->0xc2953d60d4d8f34b
ruby       7435 yuya    1     PIPE 0xc2953d60d4d8f34b      16384          ->0xc2953d60d4d8f97b
```

(7435 is spring server)
I'm using OS X 10.10.4.

**Comment by ypresto** [comment]
I just fixed it!

**Comment by jimmykarily** [comment]
Thank you @ypresto for the fix. I lost 2 days of my life debugging my application before I found this issue. It's been almost a year since the fix. Do we know when this is going to be merged?
