### ISSUE TITLE
Spring v1.6.0 broken on ruby 2.1.6

### ISSUE THREAD

**Issue by hsume2** [rails/spring#457]
I'm getting this backtrace when running `spring -v`.

```
/opt/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/spring-1.6.0/lib/spring/client.rb:6:in `require': cannot load such file -- spring/client/help (LoadError)
	from /opt/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/spring-1.6.0/lib/spring/client.rb:6:in `<top (required)>'
	from /opt/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/spring-1.6.0/bin/spring:48:in `<top (required)>'
	from /opt/.rbenv/versions/2.1.6/bin/spring:23:in `load'
	from /opt/.rbenv/versions/2.1.6/bin/spring:23:in `<main>'
```

I believe this was caused by [this line](https://github.com/sonalkr132/spring/blob/4dd5e03de4b98999a88c05ff9849e1483ed0119d/lib/spring/client/run.rb#L1). I'll see if I can figure out what the proper fix is.

**Comment by sonalkr132** [comment]
hey. Can you help me recreate this?

I did following:
```
$ rvm install 2.1.6
$ gem install spring -v 1.6.0
$ gem install bundler
$ spring -v
Spring version 1.6.0
```

Did you get error just on `spring -v`? I don't think there is any specific test for `spring -v` but [these lines](https://github.com/rails/spring/blob/521090cfc862635d90720e583f0e97e36be05616/lib/spring/test/acceptance_test.rb#L85-L95) come close.

**Comment by sonalkr132** [comment]
I added following to [acceptance test](https://github.com/sonalkr132/spring/blob/test-version/lib/spring/test/acceptance_test.rb#L105-L107):
```
test "show version" do
   assert_success "bin/spring -v", stdout: 'Spring version 1.6.0'
end
```

And following are passing travis builds of ruby 2.1.6:
[rails 4.0](https://travis-ci.org/sonalkr132/spring/jobs/97372521)
[rails 4.1](https://travis-ci.org/sonalkr132/spring/jobs/97372522)
[rails 4.2](https://travis-ci.org/sonalkr132/spring/jobs/97372523)

**Comment by sonalkr132** [comment]
Okay. I finally reproduced it. If you are inside a folder which has `Gemfile` (for example a rails app) and you don't have `gem spring` in the `Gemfile` then you get mentioned issues.
This is because of following line in `spring/commands.rb`:
```
  require "bundler/setup"
```
Bundler setup overrides the $LOAD_PATH with gems in `Gemfile` and if spring is not there, one would get
> `require': cannot load such file -- spring/client/help

It can be fixed if `require "spring"` is added after `require "bundler/setup`. There has to be a better solution than this. May be one where this confict of $LOAD_PATH doesn't occur in first place.

**Comment by hsume2** [comment]
Hey @sonalkr132 thanks for looking into this. It's hard to imagine a quick fix for this. A more involved fix would require using `require_relative` or something so we're not dependent on the $LOAD_PATH.

**Comment by RTJ** [comment]
Hello,
I has same problem, for me worked this:

```
bin/spring stop
bin/spring binstub --remove --all
bundle install && update
```

**Comment by jbodah** [comment]
:+1: 6fc09c0 fixes the issue for me as well

**Comment by jonleighton** [comment]
I don't think 6fc09c0 is the best way to fix this, see [my comment on #455](https://github.com/rails/spring/pull/455/files#r48411471)

**Comment by jonleighton** [comment]
I think v1.6.2 (just released) solves this. Please reopen if not.

**Comment by hsume2** [comment]
Thanks!

**Comment by grosser** [comment]
:heart: thx for fixing this nastiness :)
