### ISSUE TITLE
Spring stderr output causing warnings in other apps

### ISSUE THREAD

**Issue by timdorr** [rails/spring#467]
This affects RubyMine currently, but possibly others. It detects the output to stderr and thinks it's a problem with the command it's trying to run. I understand the motivation behind putting it on stderr, so I'm not sure I have a good answer.

Related: I see that I can set `Spring.quiet = true` to silence the output, but the documentation doesn't indicate where to do that. Where should I be putting that?

**Comment by sonalkr132** [comment]
You can put `Spring.quite = true` in `~/.spring.rb` or your app's `config/spring.rb`. Check out [Configuration](https://github.com/rails/spring#configuration) for further details.

**Comment by timdorr** [comment]
Figured that part out. Thanks :smile:

**Comment by njt1982** [comment]
Or maybe:
```
Spring.quiet = true
```

;-)

`s/quite/quiet/`

**Comment by thewoolleyman** [comment]
There are still situations where you don't want to put `Spring.quiet = true` in `~/.spring.rb` or your app's `config/spring.rb`, but want to enable quiet mode on a case-by-case basis. 

So, I've added support for a `SPRING_QUIET` environment variable in https://github.com/rails/spring/pull/674.
