### ISSUE TITLE
Non-timestamp initializer changes ignored

### ISSUE THREAD

**Issue by torimus** [rails/spring#470]
Hi,

I'm not sure this is a bug or spring's feature, but when there is other source of a change for an initializer (in <root>/config/initializers/) - other then file modification time, spring process is not restarted and old settings persist.

Let's assume following scenario:

 - run a rake task which launches springs' environment preload
 - alter some value in a database, one of initalizers rely upon and changes its behavior
 - run another rake task which depends on changed behavior of an initializer

The rake task would use old environment, the spring proces was not restarted.

I'm aware it would be quite difficult monitor such dependencies, but is there some way how signalize to spring from an initializer it should be reloaded ?

**Comment by grosser** [comment]
so you want spring to restart whenever the database changes ?

**Comment by torimus** [comment]
@grosser I can understand the sarcasm, but had some more generic way on mind how identify changes requiring app restart. Some kind of watchdog API, with which you can register an watched object.

This is not an uncommon experience f.E. database migrations, which may alter application's behavior. It can lead to some nasty surprising issues, when spring is not aware and old instance is still used. Surprising in just binstub executables with spring and forget …

I do understand it would introduce some additional complexity, on the other hand it'd allow avoid above described pitfalls.

**Comment by grosser** [comment]
Schema changes sounds like a good idea, but those would also change db/schema.rb -> cause a restart ?
You can try some monkey-patches in the local config/spring_client.rb to see if it works / makes sense.

**Comment by torimus** [comment]
@grosser Just got an idea implement it with use of [Observable](http://ruby-doc.org/stdlib-2.3.0/libdoc/observer/rdoc/Observable.html) from standard Ruby library and register existing triggers for an unchanged behavior, for current users. If it would prove to be effective I may send a PR.

**Comment by grosser** [comment]
or make it a blog post or wiki page to share the hacks :)
