### ISSUE TITLE
Rails console not working with spring 1.7.0

### ISSUE THREAD

**Issue by plentz** [rails/spring#480]
It takes forever and it never starts(`rails server` works as expected). Rolling back to spring `1.6.4` make it work again.

**Comment by jonleighton** [comment]
Do you still have problems with version 1.7.1?

**Comment by yanisvieilly** [comment]
Had the same issue with 1.7.0, but updating to 1.7.1 seems to have fixed it for me.

**Comment by plentz** [comment]
@jonleighton just updated. working as expected, thanks :)
