### ISSUE TITLE
problem with rails c

### ISSUE THREAD

**Issue by FructuosoRobles** [rails/spring#496]
When I try to: rails c, I get this error. I have try to fix it but had no luck.

/Users/BalioTech/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/BalioTech/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/BalioTech/Desktop/qterra/vendor/cache/ruby/2.2.0/gems/spring-1.5.0/lib/spring/commands.rb:33:in `<module:Spring>'
	from /Users/BalioTech/Desktop/qterra/vendor/cache/ruby/2.2.0/gems/spring-1.5.0/lib/spring/commands.rb:4:in `<top (required)>'
	from /Users/BalioTech/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/BalioTech/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/BalioTech/Desktop/qterra/vendor/cache/ruby/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:77:in `preload'
	from /Users/BalioTech/Desktop/qterra/vendor/cache/ruby/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:143:in `serve'
	from /Users/BalioTech/Desktop/qterra/vendor/cache/ruby/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:131:in `block in run'
	from /Users/BalioTech/Desktop/qterra/vendor/cache/ruby/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:125:in `loop'
	from /Users/BalioTech/Desktop/qterra/vendor/cache/ruby/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:125:in `run'
	from /Users/BalioTech/Desktop/qterra/vendor/cache/ruby/2.2.0/gems/spring-1.5.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/BalioTech/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/BalioTech/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by anthonylely** [comment]
Do you use sqlite3 database ?

**Comment by FructuosoRobles** [comment]
Its ok now, I update somethings I had global, restart the mac and done.

thanks

2016-10-20 8:41 GMT-05:00 Anthony Lely <notifications@github.com>:
