### ISSUE TITLE
Spring loses configuration of modules performed in initializers

### ISSUE THREAD

**Issue by exviva** [rails/spring#498]
I'm having a problem with spring losing the result of my initializer code setting some config on modules from my `lib` directory. Here's a contrived example:

```ruby
# lib/api.rb
module API
  def self.api_key=(key)
    @api_key = key
  end

  def self.call(path, params)
    raise 'API key is required' unless @api_key
    # ...
  end
end

# config/initializers/api.rb
Api.api_key = ENV['API_KEY']

# spec/lib/api_spec.rb
describe API do
  it 'makes a remote call' do
    # passes first time round, raises on subsequent calls
    expect(API.call('/foo', nil).response_code).to eq(200)
  end
end
```

I'm guessing this is because Spring reloads the `API` constant, but not the initializer. This is just a contrived example, in practice this is happening to me with any initializer code that performs module-level configuration.

Is there any way to prevent Spring from losing that initialized state?

**Comment by rafaelfranca** [comment]
This is not a spring issue. It would happen even in development without spring. This happen because initializers are not reloaded after the process started. To fix this you have to add this configuration inside a tô_prepare block.

**Comment by exviva** [comment]
Thanks for the explanation @rafaelfranca!
