### ISSUE TITLE
Rails could not find gem 'spring

### ISSUE THREAD

**Issue by JustinMi** [rails/spring#506]
Hi,

I am new to using rails. I created a new rails app and ran bundle install, and then tried running rails server. I then got this error message: 
`Could not find gem 'spring' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.`
However, in my Gemfile, it seems that I already have spring (http://pastebin.com/WHzzRXYQ). Can you help me figure this out?

Thanks so much!

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
