### ISSUE TITLE
Address already in use when using docker-compose

### ISSUE THREAD

**Issue by cerdiogenes** [rails/spring#512]
I follow the guide in https://github.com/jonleighton/spring-docker-example and everything is working smooth, except sometimes when I run `docker-compose up` and I get the following error:

```bash
spring_1    | [2017-02-02 11:15:52 +0000] [18941] [server] shutting down
spring_1    | /usr/local/bundle/gems/spring-2.0.0/lib/spring/server.rb:47:in `initialize': Address already in use - connect(2) for tmp/spring.sock (Errno::EADDRINUSE)
spring_1    | 	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/server.rb:47:in `open'
spring_1    | 	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/server.rb:47:in `start_server'
spring_1    | 	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/server.rb:43:in `boot'
spring_1    | 	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/server.rb:14:in `boot'
spring_1    | 	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/client/server.rb:10:in `call'
spring_1    | 	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
spring_1    | 	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
spring_1    | 	from /usr/local/bundle/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
spring_1    | 	from /usr/local/bundle/bin/spring:17:in `load'
spring_1    | 	from /usr/local/bundle/bin/spring:17:in `<main>'
```
Stop docker-compose and start it again solves the problem. In the first moment I thought that this happen due docker-compose not stopping a service in a past execution, but today it happened after I switch on my machine.

Any idea in how to eliminate this little annoyance?

**Comment by MrOutis** [comment]
@cerdiogenes, change your command on the spring container for: `sh -c "rm -rf tmp/spring.sock && spring server"`
sometimes, Docker can't terminate successfully its services, leaving `pids` and `sockets`.

**Comment by cerdiogenes** [comment]
Thanks for the hint @MrOutis, another appoach (I'm using it for a while) is set the option `restart: always` to the spring service in `docker-compose.yml`.
