### ISSUE TITLE
Timeout error when starting spring with a container and with env variables.

### ISSUE THREAD

**Issue by GCorbel** [rails/spring#556]
I want to use docker with spring as described [here](https://github.com/jonleighton/spring-docker-example). I created a file named `config/spring_client.rb`. It works well but I prefer to use env variable so I added, in my `~/.zshrc`, this : 

    export SPRING_SOCKET="tmp/spring.sock"
    export SPRING_SERVER_COMMAND="docker-compose up spring"

I can see variables are loaded but using `echo $SPRING_SOCKET` and it gives the values. When I do `bin/rspec ...` I have `Starting Spring server with `docker-compose up spring` timed out after 20 seconds`. The container is correctly started but `tmp/spring.sock` is not created. I tried with `$PWD/tmp/spring.sock` but I have the same result.

It's does not works with a `~/.spring.rb` file too.

If I do : 

    p ENV["SPRING_SOCKET"]
    ENV["SPRING_SOCKET"] = "tmp/spring.sock"

It shows `tmp/spring.sock` from env variables and it works.

I suppose there is a problem with file path to find and create `tmp/spring.sock` but I don't see a solution.

Do you have a solution?

**Comment by jeremy** [comment]
If setting the env vars in `config/spring_client.rb` works but setting them in `.zshrc` does not, that suggests that your container isn't running an interactive zsh shell which sources `.zshrc`, resulting in the env var never getting set. Your container probably isn't running a shell at all; you'll need to tell Docker to set that env var instead.
