### ISSUE TITLE
Is there a way to run a callback before/after a file is reloaded?

### ISSUE THREAD

**Issue by ndbroadbent** [rails/spring#578]
Hello,

I'm looking into this issue for `stripe-rails`: https://github.com/tansengming/stripe-rails/issues/136
`stripe-rails` provides a callback DSL where callbacks can be registered inside models. Whenever I change a file that has some Stripe callbacks, the file is reloaded by Spring, and this causes a duplicate callback to be registered.

I would be interested in a Spring hook that I could run before any file is reloaded, because then I could clear any previous callbacks.

I was also wondering if any other libraries might have run into a similar issue. Is there a general pattern I could use to solve this kind of problem? (E.g. Reloading a file causes multiple callbacks to be registered.)

Thanks!

**Comment by ndbroadbent** [comment]
Here is [the relevant file in `stripe-rails`](https://github.com/tansengming/stripe-rails/blob/master/lib/stripe/callbacks/builder.rb). This code defines some callback methods, and sets up some hashes to store the callbacks.

I'm thinking about modifying this code so that it also stores a reference to the class or file, so that I know where each callback was defined. I would like to have a Spring hook that is called for any files that were deleted, renamed, or modified (and before any new code is loaded). And then I would just clear any callbacks that were previously defined in that file. I think that would work.

For now I can just manually do this with the [listen](https://github.com/guard/listen) gem, but it would be good if I could access Spring's file listeners instead of adding my own.

**Comment by ndbroadbent** [comment]
Here's my solution to fix the Spring issue in `stripe-rails` - https://github.com/tansengming/stripe-rails/pull/137/files

> One very minor issue: I was able to trigger a race condition when I saved a file right when the tests started. This cleared all the callbacks after Spring had already reloaded the models, so my tests failed.

This is because I'm adding my own listener that runs in the background, so it can get out of sync if you save a file at the wrong time. If Spring provided a hook for changed files then I would be able to keep everything in sync.

**Comment by rafaelfranca** [comment]
Springs doesn't provide any callback for this because this is handled by Rails. Rails does provide callbacks for when code is reloaded. https://guides.rubyonrails.org/configuring.html#initialization-events

**Comment by ndbroadbent** [comment]
Oh awesome, thanks! I didn't realize that this was all handled by Rails.

In that case it makes much more sense to create a filewatcher and use `config.before_initialize` to clear the callbacks if any files have changed. Haha I just wrote a [blog post a few days ago about splitting up routes into different files](https://formapi.io/blog/posts/how-to-split-up-rails-routes-into-multiple-files/), and had to set up code reloading for development.

So I think that would be a good way to handle this as well. Something like:

```ruby
Rails.application.configure do
  stripe_callback_reload_paths = {
    ...
  }
  stripe_callback_reloader = config.file_watcher.new([], stripe_callback_reload_paths) do
    clear_stripe_callbacks!
  end
  reloaders << stripe_callback_reloader
  config.to_prepare { stripe_callback_reloader.execute_if_updated }
end
```

I didn't realize I could use that to solve this Spring issue as well. Thanks!
