### ISSUE TITLE
undefined method `reject!' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by brandoncc** [rails/spring#580]
I updated some gems and now when I run `bundle exec spring rails console`, I get the following error:

```
$ bundle exec spring rails console
Running via Spring preloader in process 95693
Loading development environment (Rails 4.2.11)
Traceback (most recent call last):
/Users/brandoncc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork': undefined method `reject!' for nil:NilClass (NoMethodError)
```

I don't even know where to start and I am hoping for some direction in debugging this issue.

**Comment by khalilgharbaoui** [comment]
Bump `binding_of_caller` gem version to 0.8.0 or run `bundle update binding_of_caller`
It's an underlying gem of spring. that needs updating.

**Comment by brandoncc** [comment]
I forgot to close this when I figured that out. Sorry!
