### ISSUE TITLE
Spring will attempt to sanitize a backtrace even if it's frozen (Spring/dry-monads incompatibility)

### ISSUE THREAD

**Issue by johnmaxwell** [rails/spring#609]
Thank you for your work on Spring. It's saved me a lot of seconds over the years :)

I encountered an incompatibility with rails/spring when I was installing a working with a new gem dry-monads

Repro repo: https://github.com/johnmaxwell/spring_dry_monads_break
dry-monads ticket: https://github.com/dry-rb/dry-monads/issues/115

The issue is that dry-monads raises an Error with a frozen, empty array for the backtrace, and Spring's patched raise attempts to sanitize the backtrace without checking if it is frozen. This causes an error: can't modify frozen Array (FrozenError)

https://github.com/dry-rb/dry-monads/blob/11ca509889044ea75eb7d21e2a8f1691295de92e/lib/dry/monads/do.rb#L134 
https://github.com/rails/spring/blob/ee687859008e947bc905b95121e306e2948d31c9/lib/spring/application.rb#L305

Does it make sense to check that the backtrace isn't frozen before attempting sanitization?

Spring 2.1.0
Rails 6.0.1
Ruby 2.6.5
dry-monads: 1.3.2

**Comment by timriley** [comment]
Hi @rafaelfranca, I'm interested in your reasoning behind closing this issue, if you don't mind sharing? Is this more of a "WONTFIX" situation, or are you considering a `frozen?` check before attempting to mutate backtrace arrays? FWIW, dry-monads has changed its behaviour here to accomodate spring, but this might still potentially be a source of user confusion in the future. Thanks!

**Comment by rafaelfranca** [comment]
I closed because the only ofender AFAIK was dry-monads and the behavior changed there. But I can change to check for frozeness for sure.
