### ISSUE TITLE
Is Ruby 2.7 supported?

### ISSUE THREAD

**Issue by aergonaut** [rails/spring#625]
I see Ruby 2.6.3 and `ruby-head` in the `.travis.yml` file, but I don't see an explicit mention of Ruby 2.7. The README also does not mention Ruby 2.7.

Given that `ruby-head` is currently 2.8, does Spring officially support Ruby 2.7?

**Comment by byroot** [comment]
Yes it is.

**Comment by aergonaut** [comment]
@byroot Thanks for the confirmation! There were some reservations about using Spring on my team as 2.7 was not one of the platforms listed in the Readme, so it was unclear if Spring was intended to work. This should clear that up!
