### ISSUE TITLE
"spring binstub --all" contradicts what Rails 6.1.0 "rails new" recommends

### ISSUE THREAD

**Issue by mattbrictson** [rails/spring#637]
As of Rails 6.1.0, `rails new` generates its own "spring-ified" binstubs:

```
bin/rake
bin/rails
bin/spring
```

These binstubs are _different_ than the ones that spring itself recommends. If you run `spring binstub --all` you will get a different set of files.

Prior to Rails 6.1.0, `rails new` used to call `spring binstub` to generate the `bin/spring` binstub. But as of Rails commit [72d10e21](https://github.com/rails/rails/commit/72d10e218b285c8dc28016c70614c836e5cc2560#diff-a83245368df35c610a37260d0a51041de89211857d47cfd0b2d1301a11709164L444-L448), `spring binstub` has been removed and Rails has slightly diverged from the Spring recommendations. It now uses these binstub templates: [bin/spring](https://github.com/rails/rails/blob/v6.1.0/railties/lib/rails/generators/rails/app/templates/bin/spring.tt), [bin/rake](https://github.com/rails/rails/blob/v6.1.0/railties/lib/rails/generators/rails/app/templates/bin/rake.tt), [bin/rails](https://github.com/rails/rails/blob/v6.1.0/railties/lib/rails/generators/rails/app/templates/bin/rails.tt).

Should this repository be updated to match the official Rails recommendations?

Or alternatively, should the README be updated to make it clear that you should _not_ run `spring binstub --all` for Rails 6.1 projects?

**Comment by deivid-rodriguez** [comment]
I noticed this today too.

I'd say the new templates should be ported to this repository. Spring only makes sense when used with Rails so these should match.

**Comment by mattbrictson** [comment]
Rails doesn't generate Spring binstubs anymore (as of Rails 7), so I think this issue is no longer relevant. Closing.
