### ISSUE TITLE
Spring uses AS::Dependencies.mechanism=

### ISSUE THREAD

**Issue by fxn** [rails/spring#649]
The accessor `ActiveSupport::Dependencies.mechanism` is private and deleted in Rails 7.

Rails has only one way to enable or disable reloading: `config.cache_classes`. Spring should document it requires that to be false because it reloads, and verify the flag in an initializer for robustness.

**Comment by byroot** [comment]
Ah, I just noticed the same thing today when upgrading Rails and worked on a fix: https://github.com/rails/spring/pull/651

**Comment by fxn** [comment]
@byroot I see there is an additional occurrence in https://github.com/rails/spring/blob/53d9e17d7f125969f21babefd513f502c8c04df5/lib/spring/application.rb#L202.

I don't discard coming later and replacing all this with documentation. Spring has no business manipulating the configuration of the user at its will. That configuration has to be there before we bootstrap, and nobody is telling you what you can do after it.

**Comment by byroot** [comment]
Ah good catch. Sorry I didn't do a great job here, and just directly fixed the error I was seeing.

It's also unfortunate that the true acceptance tests don't run against rails edge, which would likely have caught this.

I agree spring probably shouldn't deal with that. But maybe it could make sense to do a new major version that requires Rails 7? Since it could assume Zeitwerk it might simplify thing. Just a thought.

**Comment by fxn** [comment]
> I agree spring probably shouldn't deal with that. But maybe it could make sense to do a new major version that requires Rails 7? Since it could assume Zeitwerk it might simplify thing. Just a thought.

It's not really about Rails 7. In my view, it should just not do anything of this and be compatible with all versions. You document `config.cache_classes` must be `false` because Spring reloads. If you want to reload, that is `config.cache_classes = false` in Rails.

Then, the initializer aborts if the setting is not `false`.

**Comment by dhh** [comment]
Seems like this is still a problem. @byroot were you planning to have a look at this?

**Comment by byroot** [comment]
If I find the time yes, but it might take a while.

**Comment by fxn** [comment]
I'll do it!
