### ISSUE TITLE
Should a Puma server started from feature tests on Rails 6 fork from a Spring process?

### ISSUE THREAD

**Issue by maxwell** [rails/spring#657]
I have a Rails 6 app which uses Spring, and whenever I run a "normal" rspec unit test, my tests run quickly after my first boot of the day.

I've noticed however that when I run a JS enabled system/feature test, the first request to my server always take a boat load (30+ seconds) of time, seemingly when it is rendering the first view.  After that first request, the rest of the requests are snappy.

Perhaps I am misunderstanding Spring, but am I wrong to expect that the Capybara.server should be able to fork from a preloaded spring process?  Or would I need to somehow tell Capybara that its server is not just my rails app to boot, but also that it is spring-ified?

thanks!

**Comment by rafaelfranca** [comment]
The capybara server is not managed by spring. It should be possible to capybara to reuse the spring server but currently there is no code in spring or capybara to do that. I think it depends on how capybara starts the application. If it uses the `rails server` command it will be able to get the cache.
