### ISSUE TITLE
`Bundler.with_original_env` vs `Bundler.with_unbundled_env`

### ISSUE THREAD

**Issue by ngan** [rails/spring#669]
I believe this change has broken things for us for environments that use bundler environment variables:
https://github.com/rails/spring/pull/661/files#diff-badda36a241454b100b8aba52c978271cff008a57451d78e600fa62c3d65d8d9L96-R96

For example, if you set the `BUNDLE_PATH=some/path/to/bundle` environment variable, it's not picked up because of the `Bundler.with_unbundled_env` change.

**Comment by ngan** [comment]
@rafaelfranca I couldn't find the reason in [the PR](https://github.com/rails/spring/pull/661) for the change. Can you help clarify? Thank you!

**Comment by ngelx** [comment]
Same here. :(

**Comment by rafaelfranca** [comment]
Fixed in 7fcb7427204b0873bc32799930e7b58ff2c7e71a

**Comment by gee-forr** [comment]
Is there any chance we could get this change released as a patch-level release on 4.0? We've been unable to upgrade to spring 4.0 because our gems locations are non standard.

Much ❤️ - thanks for the gem. It saves us ridiculous amounts of time when devving on some of our larger systems

**Comment by gee-forr** [comment]
Just a smol bump to ping @rafaelfranca if it's possible to release a `4.0.1` that includes this fix?

**Comment by woohoou** [comment]
+1 with the 4.0.1 release
