### ISSUE TITLE
spring 4.0.0 bundles with rails < 6.0

### ISSUE THREAD

**Issue by AdnanTheExcellent** [rails/spring#671]
I just did a bundle update on my rails 5.2 project and it let me bundle spring 4.0.0. When i run my server i get this: `Spring only supports Rails >= 6.0.0 (RuntimeError)`. I had to lock spring in my gemfile to 3.1.1. It looks like theres no dependency for rails >= 6.0 in the gem.

**Comment by rafaelfranca** [comment]
spring can't depend on rails unfortunately, so the only way for us to tell user that a version doesn't work with some version of Rails is with the message you saw.
