### ISSUE TITLE
`rails db:system:change` command fails via spring

### ISSUE THREAD

**Issue by inayuky** [rails/spring#678]
As I reported at https://github.com/rails/rails/issues/34710#issuecomment-1140250838, `rails db:system:change` command fails only via spring.

```
% rails db:system:change --to=postgresql
Running via Spring preloader in process 15906
invalid option: --to=postgresql
```

Probably due to the following spring update.

rails/spring@b85f41b

This forces to call rake for all db commands, but exceptionally the new `db:system:change` command is not a rake task.

```
% rake db:system:change --to=postgresql
invalid option: --to=postgresql
```

The following simple fix works fine in my environment.
How about this fix?

```rails.rb
        elsif command_name&.start_with?("db:") && !command_name.start_with?("db:system")
```

**Comment by ghiculescu** [comment]
That fix looks good to me too, want to make a PR?

**Comment by inayuky** [comment]
@ghiculescu Thank you for your reply. Yes, I will make PR.
