### ISSUE TITLE
Cut new gem to include latest fix to `digest`

### ISSUE THREAD

**Issue by yjukaku** [rails/spring#680]
In https://github.com/rails/spring/pull/672 a fix was merged for apps that use bootsnap and were getting an error message similar to

> You have already activated digest 3.0.0, but your Gemfile requires digest 3.1.0. Since digest is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports digest as a default gem. (Gem::LoadError)

Is it possible to release a new gem version that includes this fix, so we can stop depending on the `main` branch in our Gemfiles? Thank you!

**Comment by rafaelfranca** [comment]
Release 4.1.0
