### ISSUE TITLE
Server leaks memory

### ISSUE THREAD

**Issue by der-flo** [rails/spring#693]
My Spring server process for a big Rails app leaks memory with every RSpec run. The amount varies, but my tests show a bigger increase when files are changed between the runs. Because we're doing BDD, the process gets enormous and slow very quickly.

Is this known behavior or specific to my use case? I worked through the documentation but couldn't find hints. Ideas to track this down further?

---

Versions:
spring 4.1.1
rails 7.0.4.2
ruby 3.1.3

**Comment by rafaelfranca** [comment]
You could use https://github.com/Shopify/heap-profiler to find what is really growing.

But since this is RSpec, there is a chance that RSpec has some internal cache that isn't being cleanup every time you run the test.

**Comment by der-flo** [comment]
@rafaelfranca Thank's for the tip! That indeed helps me to track this down further. It indeed is not clear yet wether my application or spring itself causes the issue.
I'll close this issue and eventually reopen it with more information.
